import { test } from '@playwright/test'

test.describe.serial('Login, manage schedule and appointment sequence', () => {
  test('Login and create a schedule', async ({ page }) => {
    await page.goto('/login')
    await page.locator('input[type="email"]').click()
    await page.locator('input[type="email"]').fill('dentist@fake.com')
    await page.locator('input[type="email"]').press('Tab')
    await page.locator('input[name="password"]').fill('12345678')
    await page.getByRole('button', { name: 'Log in' }).click()
    await page.getByTestId('createSchedule').click()
    await page.getByRole('textbox', { name: 'Start Date' }).fill('2024-02-11')
    await page.getByRole('textbox', { name: 'End Date' }).fill('2024-02-13')
    await page.getByRole('textbox', { name: 'Start Time' }).click()
    await page.getByRole('textbox', { name: 'Start Time' }).fill('11')
    await page.getByRole('textbox', { name: 'End Time' }).click()
    await page.getByRole('textbox', { name: 'End Time' }).fill('15')
    await page.getByRole('button', { name: 'Create Schedule' }).click()
    await page.goto('/dashboard')
  })

  test('Edit a schedule', async ({ page }) => {
    await page.goto('/login')
    await page.locator('input[type="email"]').click()
    await page.locator('input[type="email"]').fill('dentist@fake.com')
    await page.locator('input[type="email"]').press('Tab')
    await page.locator('input[name="password"]').fill('12345678')
    await page.getByRole('button', { name: 'Log in' }).click()
    await page.getByTestId('editSchedule').click()
    await page.getByRole('textbox', { name: 'End Date' }).fill('2024-02-12')
    await page.getByRole('textbox', { name: 'End Time' }).click()
    await page.getByRole('textbox', { name: 'End Time' }).fill('13')
    await page.getByRole('button', { name: 'Edit Schedule' }).click()
  })

  test('Delete a schedule', async ({ page }) => {
    await page.goto('/login')
    await page.locator('input[type="email"]').click()
    await page.locator('input[type="email"]').fill('dentist@fake.com')
    await page.locator('input[type="email"]').press('Tab')
    await page.locator('input[name="password"]').fill('12345678')
    await page.getByRole('button', { name: 'Log in' }).click()
    await page.getByTestId('editSchedule').click()
    await page.getByRole('button', { name: 'Delete Schedule' }).click()
    await page.getByRole('link', { name: 'Logout' }).click()
  })
})
